version: '3'

services:

  desafio-nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: guntzbr/desafio-nginx
    container_name: desafio-nginx
    networks:
      - desafio-network
    ports:
      - "8080:80"
    depends_on:
      - desafio-node

  desafio-node:
    build:
      context: ./node
      dockerfile: Dockerfile
    image: guntzbr/desafio-node
    container_name: desafio-node
    entrypoint: dockerize -wait tcp://desafio-db:3306 -timeout 40s docker-entrypoint.sh
    networks:
      - desafio-network
    volumes:
      - ./node:/usr/src/app
    tty: true
    ports:
      - "3000:3000"
    depends_on:
      - desafio-db
    command: node index.js  

  desafio-db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: desafio-db
    restart: always
    tty: true
    volumes: 
      - ./mysql:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment: 
      - MYSQL_DATABASE=desafio
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - desafio-network

networks:
  desafio-network:
    name: desafio-network
    driver: bridge