FROM node:18

WORKDIR /usr/src/app

RUN apt-get update && apt-get install -y wget

ENV DOCKERIZE_VERSION v0.6.1
RUN wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz

RUN npm install express --save && \
    npm install mysql --save 

COPY . .

EXPOSE 3000

ENTRYPOINT [ "node", "index.js" ]

# docker run -d -it --name desafio-node --network=desafio-network -p 3000:3000 guntzbr/desafio-node bash